basic_settings:
  site_title: Belén Rubio Ballester
  site_tagline: Welcome to my personal site
  favicon_image: /images/favicon.png

header_settings:
  avatar_image: /images/avatar.jpg
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Updates'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Publications'
      url: '/publications'
    - title: 'About'
      url: '/about'



grid_settings:
  grid_spacing: 10

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/brballester'
  instagram_url: 'https://www.instagram.com/neurorehab_sci/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/belenrubioballester/'

color_settings:
  background_color: '#ffffff'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#3c86ee'
  border_color: '#b6d3f7'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600" rel="stylesheet">'
  title_font: '"Nunito", sans-serif'
  body_font: '"Nunito", sans-serif'
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 20
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 18
    medium_size: 18
    large_size: 18
    weight: 500
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 20
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 20
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 17
    medium_size: 20
    large_size: 25
    weight: 300
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 16
    medium_size: 16
    large_size: 16
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 12
    medium_size: 14
    large_size: 14
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 13
    medium_size: 16
    large_size: 16
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 18
    medium_size: 18
    large_size: 18
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 20
    medium_size: 30
    large_size: 40
    weight: 200
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 300
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""